site_name: Anthares WriteUps
site_author: Ángel Heredia
site_description: A little page to mainly show my write ups in a pretty way
site_url: https://anthares101.com/
copyright: Copyright &copy; 2020 - 2022 Ángel Heredia
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  icon:
    logo: material/flag
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - assets/css/extra.css

extra:
  social:
    - icon: custom/mypublicinbox
      link: https://mypublicinbox.com/Anthares101
    - icon: fontawesome/brands/github
      link: https://github.com/anthares101
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angelherediaperez
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anthares101
    - icon: custom/hackthebox
      link: https://app.hackthebox.com/profile/366635
    - icon: custom/ctftime
      link: https://ctftime.org/team/133772

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
          
plugins:
  - section-index
  - search
