site_name: Anthares WriteUps
site_author: Ángel Heredia
site_description: A little page to mainly show my write ups in a pretty way
site_url: https://anthares101.github.io/
copyright: Copyright &copy; 2020 - 2021 Ángel Heredia

repo_name: Github Repository
repo_url: https://github.com/anthares101/anthares101.github.io
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  icon:
    logo: material/flag
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anthares101
    - icon: custom/ctftime
      link: https://ctftime.org/team/133772
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anthares101
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angelherediaperez

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
          
plugins:
  - section-index

